### ISSUE TITLE
Color selector button in tag list has become too large

### ISSUE THREAD

**Issue by csete** [csete/gqrx#622] opened 2018-04-15 23:36 UTC
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/gqrx/l8qfsJzub_E/iPZ0oimHBAAJ

---

It looks like the width of the color selector button has increased gradually from Qt 5.6 -> 5.9 -> 5.10.

**Comment by kukabu** [comment] 2018-05-30 05:26
The similar behavior in the "Add bookmark" window.

**Comment by kolbma** [comment] 2020-03-11 20:26
Is this still a problem? I can't reproduce it... looks always good here.

**Comment by argilo** [comment] 2020-11-29 03:52
It appears this was fixed in 2ec4f0826e9e82340e0c3a00e277c526da65c13d.

**Closed by argilo** 2020-11-29 03:52 UTC
Labels: bug
