### ISSUE TITLE
gqrx doesn't output on udp 7355 when using rtl_tcp

### ISSUE THREAD

**Issue by MichaelTrip** [csete/gqrx#877] opened 2020-11-19 20:49 UTC
Hello,

I have a rasberry pi running rtl_tcp with a sdr dongle on it. When i connect with gqrx it works fine, but it seems that it doesn't show any output on the udp 7355. I tried to use multimon-ng but i don't get any output. When i do a nc -l -u 7355 nothing happens.

**Comment by argilo** [comment] 2020-11-19 22:52
I'm not able to reproduce this with the 2.13.5 release or the current master. Can you let me know exactly which version of Gqrx you're running, and what settings you've got in your UDP configuration?

**Comment by argilo** [comment] 2020-11-28 16:11
Since no details have been provided and the feature appears to be working, I'll close this off for now.

**Closed by argilo** 2020-11-28 16:11 UTC
