### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by physiii** [csete/gqrx#526] opened 2017-07-02 00:24 UTC
Tried apt install gqrx-sdr and compiling from this repo with same result:

> $ gqrx
> linux; GNU C++ version 6.2.0 20161027; Boost_106200; UHD_003.009.005-0-unknown
> 
> Controlport disabled
> No user supplied config file. Using "default.conf"
> gr-osmosdr 0.1.4 (0.1.4) gnuradio 3.7.10
> built-in source types: file osmosdr fcd rtl rtl_tcp uhd miri hackrf bladerf rfspace airspy soapy redpitaya 
> FM demod gain: 1.52789
> IQ DCR alpha: 1.04166e-05
> Using audio backend: auto
> BookmarksFile is /home/physiii/.config/gqrx/bookmarks.csv
> Segmentation fault (core dumped)

> 
> $ lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu Artful Aardvark (development branch)
> Release:	17.10
> Codename:	artful

**Comment by csete** [comment] 2017-07-02 09:53
Please always check for known issues before reporting a problem.

Closing as duplicate of issue #452.

**Closed by csete** 2017-07-02 09:53 UTC
