### ISSUE TITLE
WFM Stereo separation disappeared?

### ISSUE THREAD

**Issue by es5nhc** [csete/gqrx#783] opened 2020-04-16 12:42 UTC
It appears that the commit 1bf1e1c2f97c635744070eca49db9bf1661062f6 has broken WFM Stereo decoding(the version of Stereo that is transmitted in the 87.5-108 MHZ band, not the OIRT one). The separation between left and right channels has become virtually zero - you might as well just stick to Mono mode. I've verified this by using test signals. In the previous commit - with a commit ID 9718d60c003b31a328b4457b400308c603e1518e, the situation with stereo audio was still normal. It seems that changing to the "new style taps" has broken something. 

As for the version of the GQRX that this is happening at, the situation is still occurring as of the current master branch state(as of 11 UTC on 16 April)

I am aware this isn't really much information, so if you have any further questions, please feel free to ask and I'll provide additional information as needed.

**Comment by argilo** [comment] 2020-04-17 03:01
Thanks for the bug report. I was able to reproduce the problem, and reverting 1bf1e1c2f97c635744070eca49db9bf1661062f6 does bring back stereo separation. I'll dig further to see if I can track down the root cause.

**Comment by argilo** [comment] 2020-04-17 03:14
I think the problem is that de-emphasis is applied too early in the receive chain. Currently it occurs right after quadrature demodulation in `rx_demod_fm`, but it should be applied separately to the left & right channels in `stereo_demod`.

**Comment by argilo** [comment] 2020-04-17 03:29
I'll take a crack at fixing this over the weekend.

**Comment by argilo** [comment] 2020-04-18 04:55
@es5nhc I've proposed a fix for this in #784.

**Closed** 2020-04-18 10:13 UTC
