### ISSUE TITLE
cursor position +10MHz and up not possible

### ISSUE THREAD

**Issue by c5e3** [csete/gqrx#582] opened 2018-01-01 17:03 UTC
gqrx v2.9-4-g4138038

i can't move the cursor further than +10MHz from center:
![image](https://user-images.githubusercontent.com/11488798/34469383-0b029408-ef1e-11e7-8ebe-1862a4911e08.png)

moving it to the far left is possible though:
![image](https://user-images.githubusercontent.com/11488798/34469384-0f48bcea-ef1e-11e7-9de7-3d44d8672e83.png)

**Comment by alexf91** [comment] 2018-01-01 17:29
This behavior is caused by two bugs:
* Frequency Widget range in the Receiver Options dock is hardcoded to 7 digits
* Frequency Widget doesn't respect range limits when the number is negative

**Comment by csete** [comment] 2018-01-01 21:07
Sounds like a bug. We should probably get rid of the "filter offset" widget, perhaps keep it as a display widget, and implement free tuning with the main frequency controller.

If it is very annoying here and now, we can probably work around this by disconnecting the spectrum display from the filter offset and you can then click on the spectrum also outside the 9.999999 MHz.

**Comment by csete** [comment] 2018-03-17 21:30
I believe it is fixed now :)
![screenshot_975](https://user-images.githubusercontent.com/306178/37560110-c24f1c7c-2a32-11e8-81f7-929c5b6f0bd9.png)

**Closed** 2018-03-18 20:38 UTC
Labels: bug
