### ISSUE TITLE
"Mirrored" signals

### ISSUE THREAD

**Issue by michelinok** [csete/gqrx#207] opened 2014-10-18 13:33 UTC
Strange problem here...
I'm not good in english...i hope to explain the problem....
I get mirrored signals around the central frequency
You can see the problem on the attached image...
Already tryed to update to the latest version of gqrx.
I've tryed the fftspectrum utility of gnuradio, and the problem is not there (llok at 144.800Mhz...it does not have the corresponding mirrored signal at 146.200Mhz).

![testmio](https://cloud.githubusercontent.com/assets/1754401/4689779/2ab6d1cc-56cb-11e4-8b76-8a4de1e48854.png)

![schermata4](https://cloud.githubusercontent.com/assets/1754401/4689770/d2dd1cc2-56ca-11e4-9872-934f64efdf80.jpg)

**Comment by pavel-i-am** [comment] 2016-06-27 14:33
I thought I was going crazy or my new board was faulty. At least now that's settled. Bug is still relevant if anyone cares, @csete . If there's any info I can help to provide, let me know.
My current setup is a Mac with El Capitan and Ettus Research b205 mini. Precompiled dmg doesn't work with the board, by the way, so I had to compile or install through macports.

**Comment by csete** [comment] 2016-06-27 19:10
I never said this bug was irrelevant, just that I think it is a duplicate of another. But if you guys prefer to have two bugs open, fine with me - it's not going to be fixed twice as fast ;-)

**Comment by pavel-i-am** [comment] 2016-06-27 22:43
@csete , I'm not complaining about statuses at all. Just letting you know that this thing might still be relevant and asking if I could be of help :)

p.s. there's a nice module gr-dsd and a fork with it embedded as a filter. Can you look at that once you have some spare time? I watched some youtube examples and it seems like a good thing to have. Cheers. (https://github.com/kantooon/gqrx_fork/tree/digital)

**Comment by csete** [comment] 2017-03-19 10:22
Duplicate of issue #99

**Closed by csete** 2017-03-19 10:22 UTC

**Comment by andimik** [comment] 2017-04-18 23:10
Same here. Sdrsharp has no mirrors, gqrx has indeed. But not always and not at all frequencies.

**Comment by csete** [comment] 2017-04-18 23:23
@andimik Please see issue #99. It has been documented for a long time now that this is a problem in gr-osmosdr and there is a workaround. A patched version of gr-osmosdr is available - again please see issue #99. Give feedback there instead of poking this closed issue.

**Comment by andimik** [comment] 2017-04-19 05:41
Google found that for me as this already known issue is NOT described in your readme. It only says one should see the issues.

There are lots of references in #99 but it's not clear for me why I should patch a 3 year old issue by myself.

So why not start a pull request for your patch?

Sorry for the questions, but I am just a user, not a programmer...

**Comment by csete** [comment] 2017-04-19 10:15
I was just pointing out that a fix is known and you can apply it if you wish. If you build everything from source, then it makes sense to apply the patch yourself. If you are using binaries, you will have to wait until the patch is available in a binary release.

The patch comes from the gr-osmosdr mailing list. I do not know why it wasn't applied upstream, so the best I can do for now is to make it available in the binaries that we distribute.
