### ISSUE TITLE
LNB frequency 9,75 and 10,6 GHz not supported

### ISSUE THREAD

**Issue by andimik** [csete/gqrx#510] opened 2017-04-15 17:44 UTC
The very common LNB frequencies for Satellite are not supported. The highest possible is 7,9 GHz.

**Comment by alexf91** [comment] 2017-04-15 17:47
Duplicate of #343

**Comment by andimik** [comment] 2017-04-15 18:10
So this issue is already open for one year...

**Comment by csete** [comment] 2017-04-15 19:15
Oddly enough, the fact that time passes does not resolve issues.

**Closed by csete** 2017-04-15 19:15 UTC
